GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blog 3",
    "author": "David Taylor",
    "url": "https://www.themarthablog.com/",
    "likes": 57
}
###
DELETE http://localhost:3003/api/blogs/69ad2b30505390201e161041
###
PUT http://localhost:3003/api/blogs/6990f821fd38609c47ab7163
Content-Type: application/json

{
    "likes": 68
}

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Law",
    "name": "Water",
    "password": "1234"
}