GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/69ab8729e4e817a59465283a
###
POST http://localhost:3001/api/notes
Content-Type: application/json

 {
    "content": "testNote1",
    "important": true,
    "userId": "69ae20a56ffeb101174dcb9f"
  }
###
DELETE http://localhost:3001/api/notes/69ab8c4478b522c05932ae30
###
PUT http://localhost:3001/api/notes/697ad60fa64c506053b8530f
Content-Type: application/json

 {
    "content": "I am a changed man1",
    "important": true
  }
###
POST http://localhost:3001/api/users
Content-Type: application/json

 {
    "username": "Dragon",
    "name": "Rogue",
    "password": "123"

  }

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "Dragon",
  "password": "123"
}